### ISSUE TITLE
Revisión del README

### ISSUE THREAD

**Issue by oscarperpinan** [aigora/twIE_2021-proyecto-mijas#1]
Hola,

He revisado el README:

- La propuesta de trabajo es adecuada, pero el equipo debe estar formado por al menos 3 estudiantes.
- Respetad el formato de la plantilla de README. Por ejemplo, falta la descripción, el segundo apartado se debe llamar "Integrantes del equipo", etc.
- Eliminad los corchetes.
- En la lista de participantes usad el formato lista de Markdown.
- Podéis enlazar cada participante a su página web de GitHub.

**Comment by DiegoFernandesAlves** [comment]
Buenas ya se han hecho los cambios, ¿está todo correctamente?

**Comment by DiegoFernandesAlves** [comment]
> Hola,
> 
> He revisado el README:
> 
> * La propuesta de trabajo es adecuada, pero el equipo debe estar formado por al menos 3 estudiantes.
> * Respetad el formato de la plantilla de README. Por ejemplo, falta la descripción, el segundo apartado se debe llamar "Integrantes del equipo", etc.
> * Eliminad los corchetes.
> * En la lista de participantes usad el formato lista de Markdown.
> * Podéis enlazar cada participante a su página web de GitHub.

Buenas ya se han hecho los cambios, ¿está todo correctamente?

**Comment by DiegoFernandesAlves** [comment]
> Hola,
> 
> He revisado el README:
> 
> * La propuesta de trabajo es adecuada, pero el equipo debe estar formado por al menos 3 estudiantes.
> * Respetad el formato de la plantilla de README. Por ejemplo, falta la descripción, el segundo apartado se debe llamar "Integrantes del equipo", etc.
> * Eliminad los corchetes.
> * En la lista de participantes usad el formato lista de Markdown.
> * Podéis enlazar cada participante a su página web

**Comment by oscarperpinan** [comment]
Insisto en que el equipo debe estar formado por al menos 3 estudiantes. Podéis admitir a otro estudiante o integraros en otro equipo.

**Comment by DiegoFernandesAlves** [comment]
> Insisto en que el equipo debe estar formado por al menos 3 estudiantes. Podéis admitir a otro estudiante o integraros en otro equipo.

Ya tenemos otro integrante solo falta ponerlo en README.

**Comment by DiegoFernandesAlves** [comment]
> > Insisto en que el equipo debe estar formado por al menos 3 estudiantes. Podéis admitir a otro estudiante o integraros en otro equipo.
> 
> Ya tenemos otro integrante solo falta ponerlo en README.

(No se como hice lo de cerrar la conversación)

**Comment by oscarperpinan** [comment]
> Ya tenemos otro integrante solo falta ponerlo en README.

Pero aún no se ha metido en el equipo. En el equipo de GitHub sólo aparecéis 2 personas.

**Comment by ignaciocartes99** [comment]
Hola Oscar, estoy intentando meterme en el equipo pero no se como.
