### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto-mijas#3]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by DiegoFernandesAlves** [comment]
De momento sólo se podrá acceder a la sección de "Cliente".
