### ISSUE TITLE
Gestión de ficheros

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto-mijas#5]
Debéis definir el **formato de los ficheros** que vuestro programa genera y lee (por ejemplo, el [formato CSV](https://es.wikipedia.org/wiki/Valores_separados_por_comas) es muy común para almacenar datos), y debéis **implementar el código** necesario para generar y leer estos ficheros.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by DiegoFernandesAlves** [comment]
Hemos creado varios ficheros en la sección de proveedores, falta rellenarlos. Se añadirán más en el mismo apartado para realizar la función final que hará interactuar al personal que utilice el programa.
También en la sección clientes varios ficheros están en proceso.
