### ISSUE TITLE
Definición de las estructuras

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto-mijas#6]
Debéis implementar la definición de las principales estructuras (datos tipo `struct`) que se usan en el programa.
Esta implementación puede tener cambios en la versión definitiva.

**Comment by DiegoFernandesAlves** [comment]
De momento sólo hemos utilizado una estructura en el apartado "clientes". Todavía hay confusión de cómo desarrollar algunos apartados y por ello no hemos avanzado mucho en este tema.
