### ISSUE TITLE
Desarrollo de las principales funciones

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto-mijas#7]
Debéis implementar las principales funciones del programa.
Esta implementación puede tener cambios en la versión definitiva. Aún no es necesario que realice todas las funcionalidades previstas.
Se recomienda el uso de librerías propias para alojar estas funciones.

**Comment by DiegoFernandesAlves** [comment]
De momento estamos desarrollando las funciones de los apartados de cliente y proveedor, que van a ser las más complejas a vista de la versión final, la cual incliye más funciones que las señaladas y comentaremos más adelante. En los apartados de publicista y agente del gobierno no hay contenido aún.
