### ISSUE TITLE
 Entrega final del código

### ISSUE THREAD

**Issue by orgynmobs** [aigora/twIE_2021-proyecto-mijas#8]
El código del trabajo debe estar completo, sin errores de compilación, y con las funcionalidades descritas en el README y en el diagrama de flujo.

Recordad que:

- Es obligatorio que el trabajo se realice con funciones.
- Es obligatorio utilizar vectores de estructuras.
- Es obligatorio utilizar ficheros.
- Está prohibido el uso de variables globales.

**Debéis cerrar esta issue cuando deis por finalizado el trabajo.**

**Comment by DiegoFernandesAlves** [comment]
Al compilarlo en distintos dispositivos aparecen errores distintos que no sabemos solucionar y por tanto pensamos que se trata de un bug. A causa de estos errores, no hemos podido comprobar si de verdad en todas la secciones se ejecuta el codigo debidamente.
